(() => {
  'use strict';
  const KEY = 'payroll_attendance_system_v1';
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
  const num = v => Number.isFinite(Number(v)) ? Number(v) : 0;
  const round2 = v => Math.round((num(v) + Number.EPSILON) * 100) / 100;
  const money = v => num(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[s]));
  const has = v => v !== null && v !== '' && v !== undefined;
  const brackets=[{max:36000,rate:.03,quick:0},{max:144000,rate:.1,quick:2520},{max:300000,rate:.2,quick:16920},{max:420000,rate:.25,quick:31920},{max:660000,rate:.3,quick:52920},{max:960000,rate:.35,quick:85920},{max:Infinity,rate:.45,quick:181920}];
  let selected='';

  function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
  function write(s){localStorage.setItem(KEY,JSON.stringify(s))}
  function monthLabel(m){if(!m)return'';const [y,n]=m.split('-');return `${y} 年 ${Number(n)} 月`}
  function employee(state,id){return (state.employees||[]).find(e=>e.id===id)}
  function clamp(v,min,max){let x=Math.max(num(v),0);if(num(min)>0)x=Math.max(x,num(min));if(num(max)>0)x=Math.min(x,num(max));return round2(x)}
  function base(state,e,type){const c=state.settings.social,b=c.bases||{},decl=num(e.socialDeclaredSalary||e.baseSalary),min=b[type+'Min'],max=b[type+'Max'];if(e.socialBaseMode==='custom'&&num(e.socialBases?.[type])>0)return round2(e.socialBases[type]);if(e.socialBaseMode==='minimum'&&num(min)>0)return round2(min);return clamp(decl,min,max)}
  function social(state,e,row){const c=state.settings.social,p=c.personal||{},er=c.employer||{},bases={pension:base(state,e,'pension'),medical:base(state,e,'medical'),unemployment:base(state,e,'unemployment'),injury:base(state,e,'injury'),housing:e.housingEnabled?base(state,e,'housing'):0};const auto={pension:round2(bases.pension*num(p.pensionRate)/100),medical:round2(bases.medical*num(p.medicalRate)/100),unemployment:round2(bases.unemployment*num(p.unemploymentRate)/100),housing:e.housingEnabled?round2(bases.housing*num(p.housingRate)/100):0};const personal={pension:has(row.pension)?round2(row.pension):auto.pension,medical:has(row.medical)?round2(row.medical):auto.medical,unemployment:has(row.unemployment)?round2(row.unemployment):auto.unemployment,housing:has(row.housing)?round2(row.housing):auto.housing};personal.total=round2(personal.pension+personal.medical+personal.unemployment+personal.housing);const employer={pension:round2(bases.pension*num(er.pensionRate)/100),medical:round2(bases.medical*num(er.medicalRate)/100),unemployment:round2(bases.unemployment*num(er.unemploymentRate)/100),injury:round2(bases.injury*num(er.injuryRate)/100),housing:e.housingEnabled?round2(bases.housing*num(er.housingRate)/100):0};employer.total=round2(employer.pension+employer.medical+employer.unemployment+employer.injury+employer.housing);return{personal,employer,bases}}
  function core(state,e,row,md){const days=Math.max(num(md.standardDays),1),rate=num(e.baseSalary)/days;let actual=has(row.actualSalaryOverride)?num(row.actualSalaryOverride):(md.salaryMode==='prorated'?rate*num(row.attendanceDays):num(e.baseSalary));const fullOk=num(row.attendanceDays)>=days&&!num(row.leaveDays)&&!num(row.absentDays)&&!num(row.lateCount)&&!num(row.lateMinutes);const full=has(row.fullAttendanceBonus)?num(row.fullAttendanceBonus):(fullOk?num(state.settings.fullAttendanceBonus):0);const leave=has(row.leaveDeductionOverride)?num(row.leaveDeductionOverride):rate*num(row.leaveDays)+rate*num(row.absentDays)*num(state.settings.absentMultiplier||1);const late=has(row.latePenaltyOverride)?num(row.latePenaltyOverride):num(row.lateCount)*num(state.settings.latePenaltyPerCount)+num(row.lateMinutes)*num(state.settings.latePenaltyPerMinute);const gross=actual+num(row.compensation)+full+num(row.salaryAdjustment)+num(row.bonus)+num(row.probationSalary)+num(row.birthdayExpense)+num(row.physicalExpense);const ss=social(state,e,row),ded=num(row.taxSupplement)+ss.personal.total+leave+late;return{actual:round2(actual),gross:round2(gross),social:ss,deduction:round2(ded),leave:round2(leave),late:round2(late),full:round2(full)}}
  function tax(state,e,target){const year=Number(target.slice(0,4)),basic=num(state.settings.tax?.monthlyBasicDeduction||5000),open=Number(e.taxOpening?.year)===year?e.taxOpening:{};let cum={months:num(open.months),income:num(open.income),exempt:num(open.exemptIncome),social:num(open.social),special:num(open.specialAdditional),other:num(open.other),relief:num(open.relief)},withheld=num(open.withheld),result={used:0};for(const m of Object.keys(state.months||{}).filter(x=>Number(x.slice(0,4))===year&&x<=target).sort()){const md=state.months[m],row=md.rows?.[e.id];if(!row)continue;const c=core(state,e,row,md),ex=num(row.taxExemptIncome),sp=has(row.specialAdditionalDeduction)?num(row.specialAdditionalDeduction):num(e.monthlySpecialAdditionalDeduction),ot=has(row.otherTaxDeduction)?num(row.otherTaxDeduction):num(e.monthlyOtherTaxDeduction),rel=num(row.taxRelief);cum.months++;cum.income+=c.gross;cum.exempt+=ex;cum.social+=c.social.personal.total;cum.special+=sp;cum.other+=ot;cum.relief+=rel;const taxable=Math.max(0,cum.income-cum.exempt-cum.months*basic-cum.social-cum.special-cum.other),b=brackets.find(x=>taxable<=x.max),pay=Math.max(0,round2(taxable*b.rate-b.quick-cum.relief)),auto=Math.max(0,round2(pay-withheld)),used=has(row.tax)?round2(row.tax):(e.taxEnabled===false?0:auto);withheld=round2(withheld+used);if(m===target)result={used,auto,taxable,rate:b.rate,quick:b.quick};}return result}
  function calc(state,e,row,md,m){const c=core(state,e,row,md),t=tax(state,e,m);return{...c,tax:t.used,net:round2(c.gross-c.deduction-t.used)}}
  function months(state){return Object.keys(state.months||{}).sort((a,b)=>b.localeCompare(a))}
  function ids(state,m){const md=state.months?.[m];return md?Object.keys(md.rows||{}).filter(id=>employee(state,id)):[]}
  function totals(state,m){const md=state.months?.[m],t={people:0,gross:0,social:0,other:0,tax:0,net:0};if(!md)return t;for(const id of ids(state,m)){const e=employee(state,id),r=md.rows[id],c=calc(state,e,r,md,m),s=c.social.personal.total,o=round2(c.deduction-s);t.people++;t.gross+=c.gross;t.social+=s;t.other+=o;t.tax+=c.tax;t.net+=c.net}for(const k of ['gross','social','other','tax','net'])t[k]=round2(t[k]);return t}
  function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function csv(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}

  function install(){if($('#historyView'))return;const sidebar=$('.sidebar'),salaryBtn=$('[data-view="salaryView"]');if(!sidebar||!salaryBtn)return;const nav=document.createElement('button');nav.className='nav-btn';nav.dataset.view='historyView';nav.innerHTML='<span class="nav-icon">历</span>历史工资';sidebar.insertBefore(nav,salaryBtn);
    const main=$('.main');const sec=document.createElement('section');sec.id='historyView';sec.className='view';sec.innerHTML=`<div class="page-heading"><div><h2>历史工资表</h2><p>自动汇总所有已保存月份，可查看历史工资条、导出并进入对应月份继续核对。</p></div><div class="toolbar no-print"><div class="field-inline"><label>查看月份</label><select id="historyMonth"></select></div><button class="btn primary" id="historyEnter">进入该月</button><button class="btn" id="historyExport">导出全部</button></div></div><div class="cards"><div class="card metric-card"><div class="metric-label"><span>已保存月份</span><span>月</span></div><div class="metric-value" id="hmMonths">0</div></div><div class="card metric-card gross"><div class="metric-label"><span>累计税前工资</span><span>¥</span></div><div class="metric-value" id="hmGross">0.00</div></div><div class="card metric-card deduction"><div class="metric-label"><span>累计扣除与个税</span><span>¥</span></div><div class="metric-value" id="hmDed">0.00</div></div><div class="card metric-card net"><div class="metric-label"><span>累计实发工资</span><span>¥</span></div><div class="metric-value" id="hmNet">0.00</div></div></div><div class="panel"><div class="panel-header"><div><h3 class="panel-title">月度汇总</h3><p class="panel-subtitle">点击查看切换下方明细。</p></div></div><div class="panel-body" style="padding:0"><div class="table-wrap" style="max-height:330px"><table style="min-width:920px"><thead><tr><th>月份</th><th>人数</th><th>税前工资</th><th>社保公积金</th><th>其他扣款</th><th>个税</th><th>实发工资</th><th>操作</th></tr></thead><tbody id="historySummary"></tbody></table></div></div></div><div class="panel"><div class="panel-header"><div><h3 class="panel-title" id="historyTitle">历史工资明细</h3><p class="panel-subtitle">工资条按所选月份生成。</p></div></div><div class="panel-body" style="padding:0"><div class="table-wrap"><table style="min-width:1080px"><thead><tr><th>姓名</th><th>出勤</th><th>实际工资</th><th>奖金及其他</th><th>税前工资</th><th>社保公积金</th><th>其他扣款</th><th>个税</th><th>实发工资</th><th>操作</th></tr></thead><tbody id="historyDetail"></tbody><tfoot id="historyFoot"></tfoot></table></div></div></div>`;main.insertBefore(sec,$('#salaryView'));
    nav.addEventListener('click',()=>{switchView();render()});$('#historyMonth').addEventListener('change',e=>{selected=e.target.value;render()});$('#historyEnter').addEventListener('click',enterMonth);$('#historyExport').addEventListener('click',exportAll);$('#historySummary').addEventListener('click',e=>{const b=e.target.closest('[data-hmonth]');if(!b)return;selected=b.dataset.hmonth;render()});$('#historyDetail').addEventListener('click',e=>{const b=e.target.closest('[data-hslip]');if(b)slip(b.dataset.hslip)});
  }
  function switchView(){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='historyView'));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='historyView'))}
  function render(){const s=read(),ms=months(s);if(!ms.includes(selected))selected=ms[0]||'';$('#historyMonth').innerHTML=ms.map(m=>`<option value="${m}" ${m===selected?'selected':''}>${monthLabel(m)}</option>`).join('')||'<option>暂无月份</option>';const all=ms.reduce((a,m)=>{const t=totals(s,m);a.g+=t.gross;a.d+=t.social+t.other+t.tax;a.n+=t.net;return a},{g:0,d:0,n:0});$('#hmMonths').textContent=ms.length;$('#hmGross').textContent=money(all.g);$('#hmDed').textContent=money(all.d);$('#hmNet').textContent=money(all.n);$('#historySummary').innerHTML=ms.map(m=>{const t=totals(s,m);return `<tr><td><strong>${monthLabel(m)}</strong></td><td>${t.people}</td><td>¥ ${money(t.gross)}</td><td>¥ ${money(t.social)}</td><td>¥ ${money(t.other)}</td><td>¥ ${money(t.tax)}</td><td class="money-result">¥ ${money(t.net)}</td><td><button class="btn small ${m===selected?'primary':''}" data-hmonth="${m}">查看</button></td></tr>`}).join('')||'<tr><td colspan="8" class="empty">暂无历史工资</td></tr>';if(!selected){$('#historyDetail').innerHTML='<tr><td colspan="10" class="empty">暂无数据</td></tr>';return}const md=s.months[selected],t=totals(s,selected);$('#historyTitle').textContent=monthLabel(selected)+'工资明细';$('#historyDetail').innerHTML=ids(s,selected).map(id=>{const e=employee(s,id),r=md.rows[id],c=calc(s,e,r,md,selected),so=c.social.personal.total,ot=round2(c.deduction-so);return `<tr><td><strong>${esc(e.name)}</strong></td><td>${num(r.attendanceDays)} 天</td><td>¥ ${money(c.actual)}</td><td>¥ ${money(c.gross-c.actual)}</td><td>¥ ${money(c.gross)}</td><td>¥ ${money(so)}</td><td>¥ ${money(ot)}</td><td>¥ ${money(c.tax)}</td><td class="money-result">¥ ${money(c.net)}</td><td><button class="btn small" data-hslip="${id}">工资条</button></td></tr>`}).join('')||'<tr><td colspan="10" class="empty">该月没有计薪员工</td></tr>';$('#historyFoot').innerHTML=`<tr><td>合计</td><td>${t.people} 人</td><td colspan="2">-</td><td>¥ ${money(t.gross)}</td><td>¥ ${money(t.social)}</td><td>¥ ${money(t.other)}</td><td>¥ ${money(t.tax)}</td><td>¥ ${money(t.net)}</td><td>-</td></tr>`}
  function enterMonth(){if(!selected)return;const s=read();s.currentMonth=selected;write(s);const picker=$('#monthPicker');if(picker){picker.value=selected;picker.dispatchEvent(new Event('change',{bubbles:true}))}const btn=$('[data-view="payrollView"]');if(btn)btn.click()}
  function exportAll(){const s=read(),rows=[['月份','姓名','出勤天数','税前工资','社保公积金','其他扣款','个人所得税','税后实发']];for(const m of months(s).reverse()){const md=s.months[m];for(const id of ids(s,m)){const e=employee(s,id),r=md.rows[id],c=calc(s,e,r,md,m),so=c.social.personal.total;rows.push([monthLabel(m),e.name,r.attendanceDays,c.gross,so,round2(c.deduction-so),c.tax,c.net])}}download('全部历史工资表.csv',rows.map(r=>r.map(csv).join(',')).join('\r\n'))}
  function slip(id){const s=read(),md=s.months[selected],e=employee(s,id),r=md?.rows?.[id];if(!e||!r)return;const c=calc(s,e,r,md,selected),income=[['实际工资',c.actual],['奖金及其他',round2(c.gross-c.actual)]].filter(x=>x[1]),ded=[['社保公积金',c.social.personal.total],['其他扣款',round2(c.deduction-c.social.personal.total)],['个人所得税',c.tax]].filter(x=>x[1]);const box=$('#slipContent');if(!box)return;box.innerHTML=`<div class="slip" id="printableSlip"><div class="slip-title">${esc(s.companyName||'工资条')}</div><div class="slip-month">${monthLabel(selected)}</div><div class="slip-head"><div><strong>姓名：</strong>${esc(e.name)}</div><div><strong>出勤：</strong>${num(r.attendanceDays)} 天</div><div><strong>银行卡：</strong>${esc(e.bankAccount?'尾号 '+e.bankAccount.slice(-4):'未填写')}</div></div><div class="slip-grid"><div class="slip-box"><h4>收入项目</h4>${income.map(x=>`<div class="slip-row"><span>${x[0]}</span><strong>¥ ${money(x[1])}</strong></div>`).join('')}<div class="slip-row"><span>税前工资</span><strong>¥ ${money(c.gross)}</strong></div></div><div class="slip-box"><h4>扣除项目</h4>${ded.map(x=>`<div class="slip-row"><span>${x[0]}</span><strong>¥ ${money(x[1])}</strong></div>`).join('')}<div class="slip-row"><span>扣除合计</span><strong>¥ ${money(c.deduction+c.tax)}</strong></div></div></div><div class="slip-net"><span>税后实发</span><span>¥ ${money(c.net)}</span></div></div>`;$('#slipModal')?.classList.add('show')}
  function start(){install();if($('#historyView'))render()}
  let tries=0;const timer=setInterval(()=>{tries++;if($('#payrollView')&&$('.sidebar')){clearInterval(timer);start()}else if(tries>40)clearInterval(timer)},100);
})();
